import Navbar from '@/components/NavBar/NavBar'
import './globals.css'
import { Montserrat } from 'next/font/google'
import styles from './globals.css'
import Footer from '@/components/Footer/Footer'
import FloatingMenu from '@/components/FloatingMenu/FloatingMenu'
import AuthProvider from '@/providers/AuthProvider'


const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <div className={styles.container}>

        <Navbar/>
        <FloatingMenu/>
        {children}
        <Footer/>
        </div>
        </AuthProvider>
        </body>
    </html>
  )
}
